# =====================================================
# TestLoopingConstructs.py ...
# =====================================================

import numpy as np

# main method ...

def main():

    print("--- Enter TestLoopingConstructs.main()       ... ");
    print("--- ======================================== ... ");

    print("--- Part 01: Exercise simple while loop ...")

    i = 1
    while i <= 10:
       print("---    i = {:.2f} ...".format(i) )
       i = i + 2

    print("--- Part 02: Simple while loop with break statement ...")

    i = 1
    while i <= 10:
       print("---    i = {:.2f} ...".format(i) )
       if i == 5:
          break
       i = i + 2

    print("--- Part 03: Simple while loop with continue statement ...")

    i = 1
    while i <= 10:
       print("---  i = {:5.2f} ...".format(i) )
       if i == 5:
          i = i + 1
          continue
       i = i + 2

    print("--- Part 04: Exercise while loop with else condition ...")

    i = 1
    while i < 6:
       print("---  i = {:.2f} ...".format(i) )
       i += 1
    else:
       print("---  i is no longer less than 6")

    print("--- Part 04: Simple for loop (shopping list) ...")

    fruits = ["apple", "peach", "banana", "cherry", "kiwi", "strawberry"]
    for x in fruits:
       print("---    Item: " + x )

    print("--- Part 05: Simple for loop with break statement ...")

    for x in fruits:
       print("---    Item: " + x )
       if x == "cherry":
          break

    print("--- Part 06: Simple for loop with range(5) function ...")

    for x in range(5):
       print("---    x = {:.2f} ...".format(x) )

    print("--- Part 07: Simple for loop with range(5,10) function ...")

    for x in range(5,10):
       print("---    x = %.2f ..." % (x) )

    print("--- Part 08: Simple for loop with range(0,10,2) function ...")

    for x in range(0,10,2):
       print("---    x = %.2f ..." % (x) )

    print("--- Part 09: Traverse array generated by np.linspace(0,10,num=11) ...")

    coords = np.linspace(0,10,num=11)
    print(coords)
    i = 0
    for item in coords:
       print("---    x({:2d}) = {:5.2f} ...".format(i, item))
       i = i + 1

    print("--- Part 10: Exercise nested for loop (adjective, fruits) ...")

    adjective = [  "red",    "big",  "tasty", "spoiled" ]
    fruits    = ["apple", "banana", "cherry"]

    for x in adjective:
       for y in fruits:
           print("---    {:s} {:s} ...".format(x, y) )

    print("--- Part 11: Use for loop to print list of cars ...")

    cars = ['Toyota', 'Honda', 'BMW', 'Tesla']
    for i in range(len(cars)):
        print("--- car {:d}: {:s} ...".format(i, cars[i]) )

    print("--- ======================================== ... ");
    print("--- Leave TestLoopingConstructs.main()       ... ");

if __name__ == "__main__":
    main()


